import type { Analytics } from '@/lib/analytics/portfolio'

export interface PortfolioAnalysis {
  summary: string
  highlights: string[]
  risks: string[]
  opportunities: string[]
  disclaimer: string
}

/**
 * Abstraction for portfolio assessment providers.
 * Deterministic analytics in v1; OpenAI is plugged in behind this interface later.
 */
export interface PortfolioAnalyzer {
  id: string
  label: string
  analyze(analytics: Analytics): Promise<PortfolioAnalysis>
}

class PlaceholderAnalyzer implements PortfolioAnalyzer {
  readonly id = 'placeholder'
  readonly label = 'Placeholder (not implemented)'

  async analyze(analytics: Analytics): Promise<PortfolioAnalysis> {
    const hold = analytics.holdingsCount
    return {
      summary: `Your portfolio is valued at ₹${Math.round(
        analytics.totalValue,
      ).toLocaleString('en-IN')} across ${hold} holding(s). AI-powered narrative assessment is coming soon.`,
      highlights: [
        `${hold} holding(s) tracked`,
        `Portfolio XIRR ${(analytics.xirr * 100).toFixed(2)}%`,
      ],
      risks: analytics.opportunities
        .filter((o) => o.severity !== 'info')
        .map((o) => o.title),
      opportunities: analytics.opportunities
        .filter((o) => o.severity === 'info')
        .map((o) => o.title),
      disclaimer: 'Generated by built-in heuristics. Enable an AI provider in Settings for narrative analysis.',
    }
  }
}

class OpenAIPortfolioAnalyzer implements PortfolioAnalyzer {
  readonly id = 'openai'
  readonly label = 'OpenAI'

  async analyze(analytics: Analytics): Promise<PortfolioAnalysis> {
    throw new Error(
      `OpenAI analyzer is not configured yet (analytics for ${analytics.holdingsCount} holding(s) computed).`,
    )
  }
}

export function getAnalyzer(enabled: boolean): PortfolioAnalyzer {
  return enabled ? new OpenAIPortfolioAnalyzer() : new PlaceholderAnalyzer()
}
